import type { GrammarQuestion } from "../types";

export const QUESTIONS: GrammarQuestion[] = [
  {
    id: "cmp-01",
    question: "Sean is usually quite ______-working, but he didn't study a lot for these exams.",
    options: ["hard", "easy", "well", "self"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Hard-working' means putting a lot of effort into work.",
  },
  {
    id: "cmp-02",
    question: "Max is ______-confident, but he knows talent is not enough to succeed.",
    options: ["well", "self", "quick", "open"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Self-confident' means having trust in one's own abilities and qualities.",
  },
  {
    id: "cmp-03",
    question: "Amber isn't very ______-minded and she doesn't like trying new things.",
    options: ["broad", "well", "open", "absent"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "'Open-minded' means willing to consider new ideas or opinions.",
  },
  {
    id: "cmp-04",
    question: "He's ______-witted and he gave fast, clever answers to the questions.",
    options: ["sharp", "quick", "half", "short"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Quick-witted' means showing and characterized by an ability to think or respond quickly and effectively.",
  },
  {
    id: "cmp-05",
    question: "You need to be ______-skinned to be a politician and ignore insensitive remarks.",
    options: ["thick", "thin", "hard", "tight"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Thick-skinned' means insensitive to criticism or insults.",
  },
  {
    id: "cmp-06",
    question: "The students are always ______-behaved in their English class.",
    options: ["good", "well", "hard", "nice"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Well-behaved' means conducting oneself in a proper and polite manner.",
  },
  {
    id: "cmp-07",
    question: "He is rude and unpleasant to everyone! He's always been bad-______.",
    options: ["mannered", "tempered", "spirited", "behaved"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Bad-tempered' means easily annoyed or angered.",
  },
  {
    id: "cmp-08",
    question: "She devotes all her time to training. She's very ambitious and self-______.",
    options: ["confident", "motivated", "behaved", "witted"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Self-motivated' means motivated to do or achieve something because of one's own enthusiasm or interest.",
  },
  {
    id: "cmp-09",
    question: "We saw a romantic comedy which was fun and quite light-______.",
    options: ["headed", "hearted", "minded", "spirited"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Light-hearted' means amusing and not serious; cheerful and carefree.",
  },
  {
    id: "cmp-10",
    question: "I've met quite a few relaxed people, but I've never known anyone as easy-______ as Mark.",
    options: ["going", "working", "talking", "tempered"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Easy-going' means relaxed and tolerant in attitude or manner.",
  },
  {
    id: "cmp-11",
    question: "My teacher is highly respected and well-______ in the academic community.",
    options: ["known", "behaved", "minded", "thought"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Well-known' means famous or widely recognized.",
  },
  {
    id: "cmp-12",
    question: "She is very sensitive to criticism; she is thin-______.",
    options: ["skinned", "headed", "hearted", "minded"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Thin-skinned' means sensitive to criticism or insults (the opposite of thick-skinned).",
  },
  {
    id: "cmp-13",
    question: "An ______-minded person is tolerant and accepts different opinions and cultures.",
    options: ["open", "absent", "narrow", "empty"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Open-minded' means willing to consider or accept new ideas and perspectives.",
  },
  {
    id: "cmp-14",
    question: "He forgets his keys all the time. He is so ______-minded.",
    options: ["absent", "weak", "narrow", "simple"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Absent-minded' means lost in thought and showing a forgetful or inattentive disposition.",
  },
  {
    id: "cmp-15",
    question: "A ______-minded person has a prejudiced, intolerant, or limited outlook.",
    options: ["narrow", "open", "broad", "strong"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Narrow-minded' means not willing to accept opinions, beliefs, or behaviors that are different from one's own.",
  },
  {
    id: "cmp-16",
    question: "This old computer is outdated; it is completely out-of-______.",
    options: ["date", "fashion", "order", "time"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Out-of-date' means old-fashioned, outdated, or no longer useful.",
  },
  {
    id: "cmp-17",
    question: "She wears the latest clothes. She is very fashion-______.",
    options: ["conscious", "designed", "known", "styled"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Fashion-conscious' means interested in and aware of the latest fashion trends.",
  },
  {
    id: "cmp-18",
    question: "The decision was made in a very cold-______ manner, showing no sympathy.",
    options: ["blooded", "hearted", "headed", "skinned"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Cold-blooded' means without feeling, mercy, or sympathy.",
  },
  {
    id: "cmp-19",
    question: "He is a very broad-______ thinker, open to global ideas.",
    options: ["minded", "hearted", "shouldered", "sighted"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Broad-minded' means tolerant or liberal in views and reactions.",
  },
  {
    id: "cmp-20",
    question: "After working all night, they were completely worn-______.",
    options: ["out", "off", "down", "up"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Worn-out' means extremely tired; exhausted.",
  },
];
