import type { GrammarQuestion } from "../types";

export const QUESTIONS: GrammarQuestion[] = [
  {
    id: "pps-01",
    question: "I had ______ the report before the meeting started.",
    options: ["finish", "finished", "finishing", "had finished"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Past Perfect Simple: had + V3. The report was completed before another past event.",
  },
  {
    id: "pps-02",
    question: "By the time the train arrived, we ______ for two hours.",
    options: ["waited", "have waited", "had waited", "were waiting"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Waiting happened before the train arrived — use past perfect simple.",
  },
  {
    id: "pps-03",
    question: "When I got home, my sister ______ dinner.",
    options: ["has cooked", "cooked", "had already cooked", "was cooked"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Cooking finished before you got home — past perfect simple.",
  },
  {
    id: "pps-04",
    question: "She ______ never ______ sushi before last night.",
    options: ["has / eaten", "had / eaten", "did / eat", "was / eating"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Before a past point ('last night'), use past perfect simple.",
  },
  {
    id: "pps-05",
    question: "They ______ each other for years before they got married.",
    options: ["knew", "have known", "had known", "were knowing"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "State verb 'know' — use past perfect simple, not continuous.",
  },
  {
    id: "pps-06",
    question: "After they ______ dinner, they went for a walk.",
    options: ["finished", "have finished", "had finished", "were finishing"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Dinner was completed before another past action — past perfect simple.",
  },
  {
    id: "pps-07",
    question: "By the time the movie started, we ______ our seats.",
    options: ["found", "have found", "had found", "were finding"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Finding seats happened earlier — past perfect simple.",
  },
  {
    id: "pps-08",
    question: "Before I moved to Tokyo, I ______ abroad.",
    options: ["never lived", "haven't lived", "had never lived", "don't live"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Use past perfect for something true before a past event.",
  },
  {
    id: "pps-09",
    question: "She ______ in two companies before she joined us.",
    options: ["worked", "has worked", "had worked", "works"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Work experience happened before another past action.",
  },
  {
    id: "pps-10",
    question: "He ______ his leg, so he couldn't play football.",
    options: ["broke", "had broken", "has broken", "was breaking"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "The injury happened before he couldn't play — past perfect simple.",
  },
  {
    id: "pps-11",
    question: "______ you ______ the email before they called you?",
    options: ["Did / send", "Have / sent", "Had / sent", "Were / sending"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Past perfect question: Had + subject + V3.",
  },
  {
    id: "pps-12",
    question: "She hadn't ______ the database before the server crashed.",
    options: ["clear", "cleared", "been clearing", "clearing"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Past perfect negative: hadn't + V3.",
  },
  {
    id: "pps-13",
    question: "By 5 PM, I ______ all the tasks.",
    options: ["completed", "have completed", "had completed", "was completing"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "'By' + past time → past perfect simple for completed result.",
  },
  {
    id: "pps-14",
    question: "I ______ him three times before he finally answered.",
    options: ["called", "have called", "had called", "was calling"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Repeated completed actions before another past event — past perfect.",
  },
  {
    id: "pps-15",
    question: "When the lights went out, we ______ the presentation.",
    options: ["didn't finish", "haven't finished", "hadn't finished", "weren't finishing"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Not finished before the lights went out — past perfect negative.",
  },
  {
    id: "pps-16",
    question: "By Monday, she ______ five reports.",
    options: ["wrote", "has written", "had written", "was writing"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Focus on result (five reports done) by a past deadline.",
  },
  {
    id: "pps-17",
    question: "They ______ the house before they bought a new one.",
    options: ["sold", "have sold", "had sold", "were selling"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Selling happened before buying — earlier past action.",
  },
  {
    id: "pps-18",
    question: "He ______ English before he moved to the UK.",
    options: ["studied", "has studied", "had studied", "was studying"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Studying was completed before moving — past perfect simple.",
  },
  {
    id: "pps-19",
    question: "I ______ never ______ such a noisy city before I visited Tokyo.",
    options: ["did / see", "have / seen", "had / seen", "was / seeing"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Experience before a past visit — past perfect with 'never'.",
  },
  {
    id: "pps-20",
    question: "By the time we arrived, the show ______.",
    options: ["started", "has started", "had started", "was starting"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "The show started before we arrived — past perfect simple.",
  },
  {
    id: "pps-21",
    question: "She ______ just ______ when I called.",
    options: ["did / leave", "has / left", "had / left", "was / leaving"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "In past narrative, 'just' + completed action → past perfect.",
  },
  {
    id: "pps-22",
    question: "We ______ to that restaurant before they closed it.",
    options: ["went", "have gone", "had gone", "were going"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Going happened before closing — earlier past event.",
  },
  {
    id: "pps-23",
    question: "He ______ in this office for six months when he got promoted.",
    options: ["worked", "has worked", "had worked", "had been working"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "With state-like completed period, simple is also possible; had worked = fact by that point.",
  },
  {
    id: "pps-24",
    question: "______ she already ______ when you arrived?",
    options: ["Has / left", "Did / leave", "Had / left", "Was / leaving"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Past perfect question about an earlier completed action.",
  },
  {
    id: "pps-25",
    question: "I ______ my keys, so I couldn't open the door.",
    options: ["lost", "have lost", "had lost", "was losing"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Losing keys happened before not being able to open — past perfect.",
  },
];
