import type { GrammarQuestion } from "../types";

export const QUESTIONS: GrammarQuestion[] = [
  {
    id: "ppc-01",
    question: "We ______ the API for three hours before we found the bug.",
    options: ["tested", "were testing", "had been testing", "have tested"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Duration before another past event — past perfect continuous.",
  },
  {
    id: "ppc-02",
    question: "We ______ for an hour when the bus finally came.",
    options: ["waited", "have waited", "had been waiting", "are waiting"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Emphasizes how long waiting continued before the bus came.",
  },
  {
    id: "ppc-03",
    question: "He was tired because he ______ all night.",
    options: ["worked", "has worked", "had been working", "was worked"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Continuous process explains the reason (tiredness) in the past.",
  },
  {
    id: "ppc-04",
    question: "Her eyes were red — she ______.",
    options: ["cried", "has cried", "had been crying", "was cried"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Visible result of an ongoing past process — past perfect continuous.",
  },
  {
    id: "ppc-05",
    question: "How long ______ you ______ before the exam?",
    options: ["did / study", "have / studied", "had / been studying", "were / study"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Asking about duration up to a past point — had been + V-ing.",
  },
  {
    id: "ppc-06",
    question: "The ground was wet because it ______.",
    options: ["rained", "has rained", "had been raining", "was rained"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Ongoing rain explains the wet ground — past perfect continuous.",
  },
  {
    id: "ppc-07",
    question: "She ______ for an hour before he arrived.",
    options: ["waited", "has waited", "had been waiting", "waits"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Focus on how long she was waiting — continuous form.",
  },
  {
    id: "ppc-08",
    question: "He hadn't ______ there long when the project closed.",
    options: ["worked", "been working", "been worked", "working"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Past perfect continuous negative: hadn't been + V-ing.",
  },
  {
    id: "ppc-09",
    question: "They ______ there for five years when they moved.",
    options: ["lived", "have lived", "had been living", "were lived"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Duration of living up to moving — past perfect continuous.",
  },
  {
    id: "ppc-10",
    question: "I ______ to call you for an hour before you answered.",
    options: ["tried", "have tried", "had been trying", "was tried"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Repeated attempts over a period — continuous emphasizes duration.",
  },
  {
    id: "ppc-11",
    question: "She was out of breath because she ______.",
    options: ["ran", "has run", "had been running", "was run"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Running process explains being out of breath.",
  },
  {
    id: "ppc-12",
    question: "______ you ______ for a long time before the manager arrived?",
    options: ["Did / wait", "Have / waited", "Had / been waiting", "Were / waited"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Past perfect continuous question: Had + subject + been + V-ing.",
  },
  {
    id: "ppc-13",
    question: "By 6 PM, I ______ the system for five hours.",
    options: ["integrated", "had integrated", "had been integrating", "was integrating"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Focus on duration of the process (five hours), not just the result.",
  },
  {
    id: "ppc-14",
    question: "She ______ since college when they finally got married.",
    options: ["dated", "has dated", "had been dating", "was dated"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "'Since' + ongoing relationship up to a past event — continuous.",
  },
  {
    id: "ppc-15",
    question: "We ______ all day, so we were exhausted.",
    options: ["studied", "have studied", "had been studying", "were studied"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "All day = duration; exhaustion is the result of the process.",
  },
  {
    id: "ppc-16",
    question: "They ______ on the project for months before it was cancelled.",
    options: ["worked", "have worked", "had been working", "were worked"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Months of ongoing work before cancellation — continuous.",
  },
  {
    id: "ppc-17",
    question: "I ______ well before the exam, so I felt tired.",
    options: ["didn't sleep", "haven't slept", "hadn't been sleeping", "wasn't slept"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Poor sleep over a period before the exam — hadn't been sleeping.",
  },
  {
    id: "ppc-18",
    question: "The team ______ the new feature when the client called.",
    options: ["developed", "has developed", "had been developing", "was developed"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Ongoing development process when interrupted — past perfect continuous.",
  },
  {
    id: "ppc-19",
    question: "He ______ English for two years before he passed the exam.",
    options: ["studied", "has studied", "had been studying", "was studied"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Two years of ongoing study — duration before a past result.",
  },
  {
    id: "ppc-20",
    question: "What ______ they ______ before the power went out?",
    options: ["did / do", "have / done", "had / been doing", "were / done"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Asking about ongoing activity before a past interruption.",
  },
  {
    id: "ppc-21",
    question: "She ______ for ten years before she retired.",
    options: ["taught", "has taught", "had been teaching", "was taught"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Ten years of teaching — emphasis on duration of the process.",
  },
  {
    id: "ppc-22",
    question: "The children ______ TV when their parents came home.",
    options: ["watched", "have watched", "had been watching", "were watched"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Ongoing activity before parents arrived — past perfect continuous.",
  },
  {
    id: "ppc-23",
    question: "By the time the meeting started, we ______ for thirty minutes.",
    options: ["discussed", "had discussed", "had been discussing", "were discussed"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Thirty minutes of discussion — focus on duration, not completion.",
  },
  {
    id: "ppc-24",
    question: "He ______ long when the company closed.",
    options: ["didn't work", "hasn't worked", "hadn't been working", "wasn't worked"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Short period of employment — hadn't been working long.",
  },
  {
    id: "ppc-25",
    question: "They ______ all night because of the deadline.",
    options: ["worked", "have worked", "had been working", "were worked"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "'All night' stresses duration of the work process.",
  },
];
