import type { GrammarQuestion } from "../types";

export const QUESTIONS: GrammarQuestion[] = [
  {
    id: "rep-01",
    question: "\"I can't come today,\" she said. -> She said that she ______ come that day.",
    options: ["can't", "couldn't", "won't", "didn't"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Present simple/modal 'can't' shifts back to past simple/modal 'couldn't' in reported speech.",
  },
  {
    id: "rep-02",
    question: "\"We have finished the project,\" they said. -> They said they ______ finished the project.",
    options: ["have", "did", "had", "would"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Present perfect 'have finished' shifts back to past perfect 'had finished'.",
  },
  {
    id: "rep-03",
    question: "\"I texted Luis an hour ago,\" Ryan told Emma. -> Ryan told Emma he ______ texted Luis an hour before.",
    options: ["has", "had", "did", "was"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Past simple 'texted' shifts back to past perfect 'had texted'.",
  },
  {
    id: "rep-04",
    question: "\"I would call you, but I lost your number,\" Tom said. -> Tom said he would call me, but he ______ lost my number.",
    options: ["had", "did", "was", "would"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Past simple 'lost' shifts back to past perfect 'had lost'. 'Would' remains unchanged.",
  },
  {
    id: "rep-05",
    question: "\"I am tired, so I'm going to bed,\" Sara said. -> Sara said she was tired, so she ______ going to bed.",
    options: ["is", "was", "has been", "went"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Present continuous 'am going' shifts back to past continuous 'was going'.",
  },
  {
    id: "rep-06",
    question: "\"Where did you go?\" she asked me. -> She asked me where I ______.",
    options: ["did go", "went", "had gone", "go"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Reported questions use statement word order and past perfect for past simple.",
  },
  {
    id: "rep-07",
    question: "\"Why are they late?\" he asked. -> He asked why they ______ late.",
    options: ["are", "were", "had been", "will be"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Present verb 'are' shifts back to past verb 'were', with statement word order.",
  },
  {
    id: "rep-08",
    question: "\"Do you like Italian food?\" she asked. -> She asked ______ I liked Italian food.",
    options: ["that", "if", "what", "did"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Yes/No questions are reported using 'if' or 'whether'.",
  },
  {
    id: "rep-09",
    question: "\"When will the train arrive?\" he asked. -> He asked when the train ______ arrive.",
    options: ["will", "would", "did", "should"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Future modal 'will' shifts back to past future 'would' in reported speech.",
  },
  {
    id: "rep-10",
    question: "\"How much does it cost?\" the man asked. -> The man asked how much it ______.",
    options: ["costs", "costed", "cost", "is costing"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Present simple 'does it cost' shifts back to past simple 'it cost' (past form of cost is cost).",
  },
  {
    id: "rep-11",
    question: "\"Have you ever been skiing?\" Rick asked us. -> Rick asked us if we ______ ever been skiing.",
    options: ["had", "did", "have", "were"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Present perfect 'have you been' shifts back to past perfect 'we had been'.",
  },
  {
    id: "rep-12",
    question: "\"I will help you tomorrow,\" Jane said. -> Jane said she would help me ______.",
    options: ["tomorrow", "yesterday", "the next day", "that day"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "'Tomorrow' shifts to 'the next day' or 'the following day' in reported speech.",
  },
  {
    id: "rep-13",
    question: "\"Don't touch the wire!\" the officer said. -> The officer warned us ______ the wire.",
    options: ["not to touch", "to not touch", "don't touch", "no touching"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Reported negative imperatives use the structure: reporting verb + object + not + to-infinitive.",
  },
  {
    id: "rep-14",
    question: "\"Please sit down,\" the teacher said. -> The teacher asked us ______ down.",
    options: ["sit", "sitting", "to sit", "please sit"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Reported requests/commands use 'ask' or 'tell' + object + to-infinitive.",
  },
  {
    id: "rep-15",
    question: "\"I bought this car yesterday,\" Mark told me. -> Mark told me he had bought that car ______.",
    options: ["yesterday", "the day before", "that day", "last day"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Yesterday' shifts to 'the day before' or 'the previous day' in reported speech.",
  },
  {
    id: "rep-16",
    question: "\"I can run very fast,\" said the boy. -> The boy said he ______ run very fast.",
    options: ["can", "could", "would", "might"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Modal 'can' shifts back to past capability 'could'.",
  },
  {
    id: "rep-17",
    question: "\"We are playing football now,\" they said. -> They said they were playing football ______.",
    options: ["now", "then", "today", "that time"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Now' shifts to 'then' or 'at that moment' in reported speech.",
  },
  {
    id: "rep-18",
    question: "\"Are you coming with us?\" they asked Emma. -> They asked Emma if she ______ coming with them.",
    options: ["is", "was", "has been", "were"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Present continuous question shifts back to past continuous statement: 'she was coming'.",
  },
  {
    id: "rep-19",
    question: "\"I must go now,\" she said. -> She said she ______ go then.",
    options: ["musted", "has to", "had to", "would"] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Modal 'must' shifts back to past obligation 'had to' in reported speech.",
  },
  {
    id: "rep-20",
    question: "\"I have been working here for years,\" she said. -> She said she had been working ______ for years.",
    options: ["here", "there", "nowhere", "that place"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Place adverb 'here' shifts to 'there' in reported speech.",
  },
];
