import type { GrammarQuestion } from "../types";

export const QUESTIONS: GrammarQuestion[] = [
  {
    id: "vpt-01",
    question: "She tried ______ the suitcase, but it was locked.",
    options: ["to open", "opening", "open", "to opening"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Try + to-infinitive' means making an effort or attempt to do something difficult.",
  },
  {
    id: "vpt-02",
    question: "I keep waking up at night. I've tried ______ to bed earlier, but it doesn't help.",
    options: ["to go", "going", "go", "to going"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Try + -ing' means experimenting with a new method to see if it solves a problem.",
  },
  {
    id: "vpt-03",
    question: "You didn't stop ______ all the way through the movie. It was very annoying!",
    options: ["to talk", "talking", "talk", "to talking"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Stop + -ing' means to cease an action that was in progress.",
  },
  {
    id: "vpt-04",
    question: "There was an icy wind, so she stopped ______ up her coat.",
    options: ["to do", "doing", "do", "to doing"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Stop + to-infinitive' means to interrupt an activity in order to do something else.",
  },
  {
    id: "vpt-05",
    question: "I don't remember ______ this T-shirt. Maybe somebody gave it to me.",
    options: ["to buy", "buying", "buy", "to buying"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Remember + -ing' means recalling a past action or event from memory.",
  },
  {
    id: "vpt-06",
    question: "Before you go to bed, please remember ______ the front door.",
    options: ["to lock", "locking", "lock", "to locking"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Remember + to-infinitive' means to not forget to perform a future task or duty.",
  },
  {
    id: "vpt-07",
    question: "I'll never forget ______ India when I was a child. It was amazing.",
    options: ["to visit", "visiting", "visit", "to visiting"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Forget + -ing' is used to talk about memories of past experiences (usually negative, like 'never forget').",
  },
  {
    id: "vpt-08",
    question: "We often forget ______ the computer off at night.",
    options: ["to turn", "turning", "turn", "to turning"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Forget + to-infinitive' means to fail to perform a duty or planned action.",
  },
  {
    id: "vpt-09",
    question: "Nicole Connolly managed ______ a lot of money for her trip.",
    options: ["to save", "saving", "save", "to saving"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Manage' is followed by the to-infinitive.",
  },
  {
    id: "vpt-10",
    question: "They decided ______ on holiday permanently.",
    options: ["to go", "going", "go", "to going"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Decide' is followed by the to-infinitive.",
  },
  {
    id: "vpt-11",
    question: "She spent some time ______ her ideas with her husband.",
    options: ["to discuss", "discussing", "discuss", "to discussing"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Spend time' is followed by the -ing form.",
  },
  {
    id: "vpt-12",
    question: "They started ______ around the world.",
    options: ["to travel", "travel", "to travelling", "travelled"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Start' can be followed by both to-infinitive and -ing; here 'to travel' is the correct option.",
  },
  {
    id: "vpt-13",
    question: "I want to avoid ______ the same mistake again.",
    options: ["to make", "making", "make", "to making"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Avoid' is always followed by the -ing form.",
  },
  {
    id: "vpt-14",
    question: "We choose ______ English because it opens career doors.",
    options: ["to study", "studying", "study", "to studying"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Choose' is followed by the to-infinitive.",
  },
  {
    id: "vpt-15",
    question: "Do you mind ______ the window? It's a bit cold.",
    options: ["to close", "closing", "close", "to closing"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Mind' is followed by the -ing form.",
  },
  {
    id: "vpt-16",
    question: "They expect ______ their results by the end of the week.",
    options: ["to receive", "receiving", "receive", "to receiving"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Expect' is followed by the to-infinitive.",
  },
  {
    id: "vpt-17",
    question: "She admitted ______ the money, but promised to return it.",
    options: ["to take", "taking", "take", "to taking"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Admit' is followed by the -ing form.",
  },
  {
    id: "vpt-18",
    question: "He promised ______ us with the relocation.",
    options: ["to help", "helping", "help", "to helping"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Promise' is followed by the to-infinitive.",
  },
  {
    id: "vpt-19",
    question: "I really enjoy ______ to this podcast.",
    options: ["to listen", "listening", "listen", "to listening"] as [string, string, string, string],
    correctIndex: 1,
    explanation: "'Enjoy' is followed by the -ing form.",
  },
  {
    id: "vpt-20",
    question: "She refused ______ to his calls after the argument.",
    options: ["to answer", "answering", "answer", "to answering"] as [string, string, string, string],
    correctIndex: 0,
    explanation: "'Refuse' is followed by the to-infinitive.",
  },
];
