export type PracticeQuestion = {
  id: string;
  textBefore: string;
  textAfter: string;
  hint: string;
  correctAnswers: string[];
};

export const PRACTICE_QUESTIONS: Record<string, PracticeQuestion[]> = {
  "perfect-tenses": [
    {
      id: "prac-perf-01",
      textBefore: "I ",
      textAfter: " (live) in this city since 2018.",
      hint: "(live)",
      correctAnswers: ["have lived", "have been living"],
    },
    {
      id: "prac-perf-02",
      textBefore: "They ",
      textAfter: " (already/finish) the project.",
      hint: "(already/finish)",
      correctAnswers: ["have already finished"],
    },
    {
      id: "prac-perf-03",
      textBefore: "She ",
      textAfter: " (never/see) a movie like this before.",
      hint: "(never/see)",
      correctAnswers: ["has never seen"],
    },
    {
      id: "prac-perf-04",
      textBefore: "By the time we got there, the plane ",
      textAfter: " (already/take off).",
      hint: "(already/take off)",
      correctAnswers: ["had already taken off"],
    },
    {
      id: "prac-perf-05",
      textBefore: "He was tired because he ",
      textAfter: " (work) for eight hours.",
      hint: "(work)",
      correctAnswers: ["had worked", "had been working"],
    },
    {
      id: "prac-perf-06",
      textBefore: "Next month they ",
      textAfter: " (be) married for ten years.",
      hint: "(be)",
      correctAnswers: ["will have been"],
    },
    {
      id: "prac-perf-07",
      textBefore: "We ",
      textAfter: " (not/hear) from him for weeks.",
      hint: "(not/hear)",
      correctAnswers: ["have not heard", "haven't heard"],
    },
    {
      id: "prac-perf-08",
      textBefore: "By tomorrow morning, I ",
      textAfter: " (complete) the assignment.",
      hint: "(complete)",
      correctAnswers: ["will have completed"],
    },
    {
      id: "prac-perf-09",
      textBefore: "When I arrived, they ",
      textAfter: " (eat) dinner, so the table was empty.",
      hint: "(eat)",
      correctAnswers: ["had eaten"],
    },
    {
      id: "prac-perf-10",
      textBefore: "How long ",
      textAfter: " you (study) English?",
      hint: "(study)",
      correctAnswers: ["have you studied", "have you been studying"],
    },
  ],
  "past-perfect-simple": [
    {
      id: "prac-pps-01",
      textBefore: "She was hungry because she ",
      textAfter: " (not/eat) anything all morning.",
      hint: "(not/eat)",
      correctAnswers: ["had not eaten", "hadn't eaten"],
    },
    {
      id: "prac-pps-02",
      textBefore: "When the film started, they ",
      textAfter: " (already/arrive).",
      hint: "(already/arrive)",
      correctAnswers: ["had already arrived"],
    },
    {
      id: "prac-pps-03",
      textBefore: "I realized I ",
      textAfter: " (leave) my keys in the office.",
      hint: "(leave)",
      correctAnswers: ["had left"],
    },
    {
      id: "prac-pps-04",
      textBefore: "He showed us the photos he ",
      textAfter: " (take) during the trip.",
      hint: "(take)",
      correctAnswers: ["had taken"],
    },
    {
      id: "prac-pps-05",
      textBefore: "The thief ",
      textAfter: " (escape) by the time the police arrived.",
      hint: "(escape)",
      correctAnswers: ["had escaped"],
    },
    {
      id: "prac-pps-06",
      textBefore: "We ",
      textAfter: " (finish) dinner before they came.",
      hint: "(finish)",
      correctAnswers: ["had finished"],
    },
    {
      id: "prac-pps-07",
      textBefore: "He failed because he ",
      textAfter: " (not/study) at all.",
      hint: "(not/study)",
      correctAnswers: ["had not studied", "hadn't studied"],
    },
    {
      id: "prac-pps-08",
      textBefore: "The teacher asked if we ",
      textAfter: " (do) the homework.",
      hint: "(do)",
      correctAnswers: ["had done"],
    },
    {
      id: "prac-pps-09",
      textBefore: "I went to bed after I ",
      textAfter: " (turn off) the lights.",
      hint: "(turn off)",
      correctAnswers: ["had turned off"],
    },
    {
      id: "prac-pps-10",
      textBefore: "They sold the house that they ",
      textAfter: " (buy) five years before.",
      hint: "(buy)",
      correctAnswers: ["had bought"],
    },
  ],
  "past-perfect-continuous": [
    {
      id: "prac-ppc-01",
      textBefore: "They ",
      textAfter: " (play) tennis for two hours when it started to rain.",
      hint: "(play)",
      correctAnswers: ["had been playing"],
    },
    {
      id: "prac-ppc-02",
      textBefore: "She was out of breath because she ",
      textAfter: " (run).",
      hint: "(run)",
      correctAnswers: ["had been running"],
    },
    {
      id: "prac-ppc-03",
      textBefore: "His hands were dirty because he ",
      textAfter: " (repair) the car.",
      hint: "(repair)",
      correctAnswers: ["had been repairing"],
    },
    {
      id: "prac-ppc-04",
      textBefore: "I ",
      textAfter: " (wait) for an hour before the bus finally came.",
      hint: "(wait)",
      correctAnswers: ["had been waiting"],
    },
    {
      id: "prac-ppc-05",
      textBefore: "He was exhausted because he ",
      textAfter: " (work) since 6 a.m.",
      hint: "(work)",
      correctAnswers: ["had been working"],
    },
    {
      id: "prac-ppc-06",
      textBefore: "The ground was wet because it ",
      textAfter: " (rain) all night.",
      hint: "(rain)",
      correctAnswers: ["had been raining"],
    },
    {
      id: "prac-ppc-07",
      textBefore: "They ",
      textAfter: " (argue) for hours before reaching a decision.",
      hint: "(argue)",
      correctAnswers: ["had been arguing"],
    },
    {
      id: "prac-ppc-08",
      textBefore: "The children ",
      textAfter: " (watch) TV before their parents told them to sleep.",
      hint: "(watch)",
      correctAnswers: ["had been watching"],
    },
    {
      id: "prac-ppc-09",
      textBefore: "She ",
      textAfter: " (study) English for years before she moved to London.",
      hint: "(study)",
      correctAnswers: ["had been studying"],
    },
    {
      id: "prac-ppc-10",
      textBefore: "How long ",
      textAfter: " they (talk) on the phone when you cut them off?",
      hint: "(talk)",
      correctAnswers: ["had they been talking"],
    },
  ],
  conditionals: [
    {
      id: "prac-cond-01",
      textBefore: "If it rains, we ",
      textAfter: " (stay) at home.",
      hint: "(stay)",
      correctAnswers: ["will stay"],
    },
    {
      id: "prac-cond-02",
      textBefore: "If I had a million dollars, I ",
      textAfter: " (buy) a house.",
      hint: "(buy)",
      correctAnswers: ["would buy"],
    },
    {
      id: "prac-cond-03",
      textBefore: "If she ",
      textAfter: " (study) harder, she would have passed the exam.",
      hint: "(study)",
      correctAnswers: ["had studied"],
    },
    {
      id: "prac-cond-04",
      textBefore: "Ice melts if you ",
      textAfter: " (heat) it.",
      hint: "(heat)",
      correctAnswers: ["heat"],
    },
    {
      id: "prac-cond-05",
      textBefore: "If I ",
      textAfter: " (know) her number, I would call her now.",
      hint: "(know)",
      correctAnswers: ["knew"],
    },
    {
      id: "prac-cond-06",
      textBefore: "If we had driven faster, we ",
      textAfter: " (arrive) before six.",
      hint: "(arrive)",
      correctAnswers: ["would have arrived"],
    },
    {
      id: "prac-cond-07",
      textBefore: "If you ",
      textAfter: " (not/hurry), you will miss the train.",
      hint: "(not/hurry)",
      correctAnswers: ["don't hurry", "do not hurry"],
    },
    {
      id: "prac-cond-08",
      textBefore: "I would be very happy if you ",
      textAfter: " (come) to the party.",
      hint: "(come)",
      correctAnswers: ["came"],
    },
    {
      id: "prac-cond-09",
      textBefore: "If he had had enough time, he ",
      textAfter: " (finish) the test.",
      hint: "(finish)",
      correctAnswers: ["would have finished"],
    },
    {
      id: "prac-cond-10",
      textBefore: "Plants die if they ",
      textAfter: " (not/get) enough water.",
      hint: "(not/get)",
      correctAnswers: ["don't get", "do not get"],
    },
  ],
  "passive-voice": [
    {
      id: "prac-pass-01",
      textBefore: "This house ",
      textAfter: " (build) in 1990.",
      hint: "(build)",
      correctAnswers: ["was built"],
    },
    {
      id: "prac-pass-02",
      textBefore: "The rooms ",
      textAfter: " (clean) every day by the staff.",
      hint: "(clean)",
      correctAnswers: ["are cleaned"],
    },
    {
      id: "prac-pass-03",
      textBefore: "A new road ",
      textAfter: " (construct) in our area at the moment.",
      hint: "(construct)",
      correctAnswers: ["is being constructed"],
    },
    {
      id: "prac-pass-04",
      textBefore: "The report ",
      textAfter: " (write) by tomorrow afternoon.",
      hint: "(write)",
      correctAnswers: ["will be written"],
    },
    {
      id: "prac-pass-05",
      textBefore: "All the cookies ",
      textAfter: " (eat) before the guests arrived.",
      hint: "(eat)",
      correctAnswers: ["had been eaten"],
    },
    {
      id: "prac-pass-06",
      textBefore: "The results ",
      textAfter: " (announce) yesterday.",
      hint: "(announce)",
      correctAnswers: ["were announced"],
    },
    {
      id: "prac-pass-07",
      textBefore: "Spanish ",
      textAfter: " (speak) in many South American countries.",
      hint: "(speak)",
      correctAnswers: ["is spoken"],
    },
    {
      id: "prac-pass-08",
      textBefore: "The car ",
      textAfter: " (repair) right now by the mechanic.",
      hint: "(repair)",
      correctAnswers: ["is being repaired"],
    },
    {
      id: "prac-pass-09",
      textBefore: "Active: Someone stole my purse. -> Passive: My purse ",
      textAfter: " (steal).",
      hint: "(steal)",
      correctAnswers: ["was stolen"],
    },
    {
      id: "prac-pass-10",
      textBefore: "The contract must ",
      textAfter: " (sign) before Friday.",
      hint: "(sign)",
      correctAnswers: ["be signed"],
    },
  ],
  "modal-verbs": [
    {
      id: "prac-mod-01",
      textBefore: "You ",
      textAfter: " (must/should) wear a seatbelt while driving. It is the law.",
      hint: "(must)",
      correctAnswers: ["must"],
    },
    {
      id: "prac-mod-02",
      textBefore: "I ",
      textAfter: " (ability) swim when I was five.",
      hint: "(could)",
      correctAnswers: ["could"],
    },
    {
      id: "prac-mod-03",
      textBefore: "It's late. We ",
      textAfter: " (should/can) go home now.",
      hint: "(should)",
      correctAnswers: ["should"],
    },
    {
      id: "prac-mod-04",
      textBefore: "Take an umbrella. It ",
      textAfter: " (possibility) rain later.",
      hint: "(might/may)",
      correctAnswers: ["might", "may"],
    },
    {
      id: "prac-mod-05",
      textBefore: "She ",
      textAfter: " (not/can) speak Chinese yet, but she is learning.",
      hint: "(cannot)",
      correctAnswers: ["cannot", "can't"],
    },
    {
      id: "prac-mod-06",
      textBefore: "You ",
      textAfter: " (not/must) smoke in the hospital. It is prohibited.",
      hint: "(must not)",
      correctAnswers: ["must not", "mustn't"],
    },
    {
      id: "prac-mod-07",
      textBefore: "I ",
      textAfter: " (necessity) study hard tonight for tomorrow's exam.",
      hint: "(have to)",
      correctAnswers: ["have to", "need to"],
    },
    {
      id: "prac-mod-08",
      textBefore: "Excuse me, ",
      textAfter: " I open the window?",
      hint: "(permission)",
      correctAnswers: ["may", "can", "could"],
    },
    {
      id: "prac-mod-09",
      textBefore: "You ",
      textAfter: " (advice) see a doctor about that cough.",
      hint: "(should/ought to)",
      correctAnswers: ["should", "ought to"],
    },
    {
      id: "prac-mod-10",
      textBefore: "He ",
      textAfter: " (not/need to) wake up early tomorrow because it's Saturday.",
      hint: "(doesn't need to)",
      correctAnswers: ["doesn't need to", "does not need to", "needn't"],
    },
  ],
  articles: [
    {
      id: "prac-art-01",
      textBefore: "He is studying to be ",
      textAfter: " doctor.",
      hint: "(a/an/the/-)",
      correctAnswers: ["a"],
    },
    {
      id: "prac-art-02",
      textBefore: "Would you like ",
      textAfter: " apple?",
      hint: "(a/an/the/-)",
      correctAnswers: ["an"],
    },
    {
      id: "prac-art-03",
      textBefore: "I want to see ",
      textAfter: " Eiffel Tower in Paris.",
      hint: "(a/an/the/-)",
      correctAnswers: ["the"],
    },
    {
      id: "prac-art-04",
      textBefore: "We go to school by ",
      textAfter: " bus.",
      hint: "(a/an/the/-)",
      correctAnswers: ["-", "zero", "no article"],
    },
    {
      id: "prac-art-05",
      textBefore: "She is ",
      textAfter: " tallest girl in our class.",
      hint: "(a/an/the/-)",
      correctAnswers: ["the"],
    },
    {
      id: "prac-art-06",
      textBefore: "Can you pass me ",
      textAfter: " salt, please?",
      hint: "(a/an/the/-)",
      correctAnswers: ["the"],
    },
    {
      id: "prac-art-07",
      textBefore: "I love listening to ",
      textAfter: " music.",
      hint: "(a/an/the/-)",
      correctAnswers: ["-", "zero", "no article"],
    },
    {
      id: "prac-art-08",
      textBefore: "We had dinner in ",
      textAfter: " excellent restaurant last night.",
      hint: "(a/an/the/-)",
      correctAnswers: ["an"],
    },
    {
      id: "prac-art-09",
      textBefore: "He plays ",
      textAfter: " piano very well.",
      hint: "(a/an/the/-)",
      correctAnswers: ["the"],
    },
    {
      id: "prac-art-10",
      textBefore: "I bought a book. ",
      textAfter: " book is very interesting.",
      hint: "(a/an/the/-)",
      correctAnswers: ["the"],
    },
  ],
  "reported-speech": [
    {
      id: "prac-rep-01",
      textBefore: "Direct: 'I can't come today,' she said. -> Reported: She said that she ",
      textAfter: " come that day.",
      hint: "(could not / couldn't)",
      correctAnswers: ["could not", "couldn't"],
    },
    {
      id: "prac-rep-02",
      textBefore: "Direct: 'We have finished the project,' they said. -> Reported: They said they ",
      textAfter: " finished the project.",
      hint: "(had)",
      correctAnswers: ["had"],
    },
    {
      id: "prac-rep-03",
      textBefore: "Direct: 'I texted Luis an hour ago,' Ryan told Emma. -> Reported: Ryan told Emma he ",
      textAfter: " texted Luis an hour before.",
      hint: "(had)",
      correctAnswers: ["had"],
    },
    {
      id: "prac-rep-04",
      textBefore: "Direct: 'I am tired, so I'm going to bed,' Sara said. -> Reported: Sara said she was tired, so she ",
      textAfter: " going to bed.",
      hint: "(was)",
      correctAnswers: ["was"],
    },
    {
      id: "prac-rep-05",
      textBefore: "Direct: 'Where did you go?' she asked me. -> Reported: She asked me where I ",
      textAfter: " .",
      hint: "(had gone)",
      correctAnswers: ["had gone"],
    },
    {
      id: "prac-rep-06",
      textBefore: "Direct: 'Why are they late?' he asked. -> Reported: He asked why they ",
      textAfter: " late.",
      hint: "(were)",
      correctAnswers: ["were"],
    },
    {
      id: "prac-rep-07",
      textBefore: "Direct: 'Do you like Italian food?' she asked. -> Reported: She asked ",
      textAfter: " I liked Italian food.",
      hint: "(if / whether)",
      correctAnswers: ["if", "whether"],
    },
    {
      id: "prac-rep-08",
      textBefore: "Direct: 'When will the train arrive?' he asked. -> Reported: He asked when the train ",
      textAfter: " arrive.",
      hint: "(would)",
      correctAnswers: ["would"],
    },
    {
      id: "prac-rep-09",
      textBefore: "Direct: 'How much does it cost?' the man asked. -> Reported: The man asked how much it ",
      textAfter: " .",
      hint: "(cost)",
      correctAnswers: ["cost"],
    },
    {
      id: "prac-rep-10",
      textBefore: "Direct: 'Have you ever been skiing?' Rick asked us. -> Reported: Rick asked us if we ",
      textAfter: " ever been skiing.",
      hint: "(had)",
      correctAnswers: ["had"],
    },
  ],
  "compound-adjectives": [
    {
      id: "prac-cmp-01",
      textBefore: "Sean is usually quite ",
      textAfter: " -working, but he didn't study a lot for these exams.",
      hint: "(hard)",
      correctAnswers: ["hard"],
    },
    {
      id: "prac-cmp-02",
      textBefore: "Max is ",
      textAfter: " -confident, but he knows talent is not enough to succeed.",
      hint: "(self)",
      correctAnswers: ["self"],
    },
    {
      id: "prac-cmp-03",
      textBefore: "Amber isn't very ",
      textAfter: " -minded and she doesn't like trying new things.",
      hint: "(open)",
      correctAnswers: ["open"],
    },
    {
      id: "prac-cmp-04",
      textBefore: "He's ",
      textAfter: " -witted and he gave fast answers to the questions.",
      hint: "(quick)",
      correctAnswers: ["quick"],
    },
    {
      id: "prac-cmp-05",
      textBefore: "You need to be ",
      textAfter: " -skinned to be a politician.",
      hint: "(thick)",
      correctAnswers: ["thick"],
    },
    {
      id: "prac-cmp-06",
      textBefore: "The students are always ",
      textAfter: " -behaved in their English class.",
      hint: "(well)",
      correctAnswers: ["well"],
    },
    {
      id: "prac-cmp-07",
      textBefore: "He is rude and unpleasant! He's always been bad-",
      textAfter: " .",
      hint: "(tempered)",
      correctAnswers: ["tempered"],
    },
    {
      id: "prac-cmp-08",
      textBefore: "You'd have to be very thick-",
      textAfter: " not to be upset by his remarks.",
      hint: "(skinned)",
      correctAnswers: ["skinned"],
    },
    {
      id: "prac-cmp-09",
      textBefore: "She is very ambitious and self-",
      textAfter: " when it comes to achieving goals.",
      hint: "(motivated)",
      correctAnswers: ["motivated"],
    },
    {
      id: "prac-cmp-10",
      textBefore: "I've met quite a few relaxed people, but none as easy-",
      textAfter: " as Mark.",
      hint: "(going)",
      correctAnswers: ["going"],
    },
  ],
  "verb-patterns": [
    {
      id: "prac-vpt-01",
      textBefore: "She tried ",
      textAfter: " (open) her suitcase, but it was impossible without the key.",
      hint: "(to open / open)",
      correctAnswers: ["to open"],
    },
    {
      id: "prac-vpt-02",
      textBefore: "I'm not surprised you found the film confusing — you didn't stop ",
      textAfter: " (talk) all the way through!",
      hint: "(talking / talk)",
      correctAnswers: ["talking"],
    },
    {
      id: "prac-vpt-03",
      textBefore: "I keep waking up at night. I've tried ",
      textAfter: " (go) to bed earlier, but it doesn't help.",
      hint: "(going / go)",
      correctAnswers: ["going"],
    },
    {
      id: "prac-vpt-04",
      textBefore: "I'll never forget ",
      textAfter: " (visit) India when I was a child.",
      hint: "(visiting / visit)",
      correctAnswers: ["visiting"],
    },
    {
      id: "prac-vpt-05",
      textBefore: "I don't remember ",
      textAfter: " (buy) this T-shirt. Maybe somebody gave it to me.",
      hint: "(buying / buy)",
      correctAnswers: ["buying"],
    },
    {
      id: "prac-vpt-06",
      textBefore: "We often forget ",
      textAfter: " (turn) the computer off at night.",
      hint: "(turning / turn)",
      correctAnswers: ["turning"],
    },
    {
      id: "prac-vpt-07",
      textBefore: "Before you go to bed, please remember ",
      textAfter: " (lock) the front door.",
      hint: "(to lock / lock)",
      correctAnswers: ["to lock"],
    },
    {
      id: "prac-vpt-08",
      textBefore: "There was an icy wind, so she stopped ",
      textAfter: " (do) up her coat.",
      hint: "(to do / do)",
      correctAnswers: ["to do"],
    },
    {
      id: "prac-vpt-09",
      textBefore: "Nicole Connolly managed ",
      textAfter: " (save) some money.",
      hint: "(to save / save)",
      correctAnswers: ["to save"],
    },
    {
      id: "prac-vpt-10",
      textBefore: "I want to avoid ",
      textAfter: " (make) the same mistake again.",
      hint: "(making / make)",
      correctAnswers: ["making"],
    },
  ],
};
